# Generated by Django 6.1.2 on 2026-10-08 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("name_en", models.CharField(max_length=150)),
                ("name_ne", models.CharField(max_length=150)),
                ("note_en", models.CharField(blank=True, max_length=255)),
                ("note_ne", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        default="📄", help_text="Emoji used on cards", max_length=8
                    ),
                ),
                ("name_en", models.CharField(max_length=120)),
                ("name_ne", models.CharField(max_length=120)),
                ("tagline_en", models.CharField(max_length=255)),
                ("tagline_ne", models.CharField(max_length=255)),
                ("overview_en", models.TextField(blank=True)),
                ("overview_ne", models.TextField(blank=True)),
                (
                    "office_en",
                    models.CharField(
                        help_text="Which office handles this service", max_length=200
                    ),
                ),
                ("office_ne", models.CharField(max_length=200)),
                ("fee_en", models.CharField(blank=True, max_length=200)),
                ("fee_ne", models.CharField(blank=True, max_length=200)),
                ("timeline_en", models.CharField(blank=True, max_length=200)),
                ("timeline_ne", models.CharField(blank=True, max_length=200)),
                (
                    "deadline_en",
                    models.CharField(
                        blank=True,
                        help_text="Statutory deadline, e.g. register within 35 days",
                        max_length=200,
                    ),
                ),
                ("deadline_ne", models.CharField(blank=True, max_length=200)),
                ("tips_en", models.TextField(blank=True)),
                ("tips_ne", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="SiteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(default="default", unique=True)),
                ("label_en", models.CharField(max_length=150)),
                ("label_ne", models.CharField(max_length=150)),
                ("value_en", models.CharField(max_length=400)),
                ("value_ne", models.CharField(max_length=400)),
                ("icon", models.CharField(default="ℹ️", max_length=8)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WorkingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Sunday"),
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                        ],
                        unique=True,
                    ),
                ),
                (
                    "open_time",
                    models.TimeField(blank=True, help_text="Blank = closed", null=True),
                ),
                ("close_time", models.TimeField(blank=True, null=True)),
                ("note_en", models.CharField(blank=True, max_length=255)),
                ("note_ne", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["day"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_en",
                    models.CharField(help_text="e.g. Your documents", max_length=120),
                ),
                ("group_ne", models.CharField(max_length=120)),
                ("label_en", models.CharField(max_length=255)),
                ("label_ne", models.CharField(max_length=255)),
                ("note_en", models.CharField(blank=True, max_length=255)),
                ("note_ne", models.CharField(blank=True, max_length=255)),
                ("required", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(max_length=255)),
                ("title_ne", models.CharField(max_length=255)),
                ("detail_en", models.TextField(blank=True)),
                ("detail_ne", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
